extends: "eslint:recommended"

parser: "babel-eslint"

parserOptions:
    ecmaVersion:    6
    sourceType:     "module"
    allowImportExportEverywhere: false

env:
    node:     true
    browser:  false

rules:
    no-unused-vars: "off"
    no-console: "off"