extends: "eslint:recommended"

parser: "babel-eslint"

env:
    node:       true
    browser:    false
    mocha:      true

parserOptions:
    ecmaVersion:    6
    sourceType:     "module"
    allowImportExportEverywhere: false

rules:
    no-unused-vars: 0
    no-console: 1
    no-case-declarations: 0
    semi: 2
